### ISSUE TITLE
Sometimes after queue instance restart consumer may receive the error 'Duplicate key exist'

### ISSUE THREAD

**Issue by Kasen** [tarantool/queue#111] opened 2020-02-27 06:23 UTC
This error is caused by a persisting state of _queue_consumer space.

**Comment by Totktonada** [comment] 2020-07-08 00:17
What method raises this error?

Whether it appears on 1.0.6?

**Comment by Totktonada** [comment] 2020-12-21 01:42
BTW, `_queue_consumer` is the temporary space, so I doubt that the problem was here.

Anyway, whether the problem appears on the new version (we have 1.0.8 now)?

**Comment by Totktonada** [comment] 2022-01-09 02:48
What also worth to know: whether it is a singleton instance? If not and it is a set of instances that replicate data to each other, we should know the topology and where exactly the problem occurs (say, 'on a current master when a past master joins back as a replica after disconnecting due to a short network connectivity issue'). Timings are matter: we should look at logs from all instances around the time when the problem occurs and should know `box.cfg()` values (`replication_timeout` and `replication_connect_timeout` at least).

I guess the problem is related to replication. There are known problems with the module around master-replica switch. We'll resolve them in #120.

I doubt I'll receive a feedback after 1.5 years of silence, so I'll close the issue. But if I'm wrong and you can provide helpful details, I would appreciate it. Feel free to reopen the issue in the case.

(I would also note that there were several fixes around task state consitency across restarts in [past releases](https://github.com/tarantool/queue/releases).)

**Closed by Totktonada** 2022-01-09 02:48 UTC
Labels: bug, need feedback
