### ISSUE TITLE
wtf bug in queue

### ISSUE THREAD

**Issue by toidi** [tarantool/queue#26] opened 2015-07-27 09:03 UTC
Config file: `/etc/tarantool/instances.enabled/queue.lua`
```
#!/usr/bin/env tarantool

box.cfg{
  listen = '3301'
}

queue = require('queue')
queue.start()

local tube_name = 'trash'
if queue.tube[tube_name] == null then
   queue.create_tube(tube_name, 'fifottl')
end
```

After `tarantoolctl restart queue` I got the following lines in log file:
```
2015-07-27 11:54:28.907 [17059] main C> got signal 15 - Terminated
Start failed: /usr/share/tarantool/queue/abstract.lua:287: attempt to index field '_queue' (a nil value)
2015-07-27 11:54:29.910 [18572] main/101/tarantoolctl C> version 1.6.5-274-gf84ad58
```

I can not reproduce this bug.

Tarantool packages:
```
tarantool-debug-1.5.3-79.x86_64
tarantool-queue-0.0.1-32.noarch
tarantool-common-1.6.5-274.noarch
tarantool-1.6.5-274.x86_64
```

**Comment by rybakit** [comment] 2015-09-04 11:58
@toidi  There is a typo in your `queue.lua`, it should be `nil` instead of `null`. Maybe this is the cause of the issue?

**Comment by kostja** [comment] 2015-09-05 08:22
Eugene,  would you like to get commit rights  to queue?

**Comment by bigbes** [comment] 2015-09-08 14:06
Are you still experiencing this problem?

**Comment by rybakit** [comment] 2015-09-09 11:46
@kostja I doubt I'll need it anytime soon, but eventually it'll be handy i guess.

**Comment by toidi** [comment] 2015-09-14 06:28
@bigbes, I unable to reproduce this bug. So far question can still be open.

**Comment by bigbes** [comment] 2016-03-04 12:14
It seems like it've been fixed in latest master. Please, feel free to reopen this bug if you expecting this problem.

**Closed by bigbes** 2016-03-04 12:14 UTC
